import { HttpStatus } from '@nestjs/common';

export const PRISMA_CLIENT_ERROR_MESSAGES = {
  UNIQUE_CONSTRAINT_VIOLATION: 'Unique constraint violation',
  COULD_NOT_FIND_YOUR_ENTITY: 'Could not find your entity',
};

export enum PRISMA_CLIENT_ERROR_CODES {
  UNIQUE_CONSTRAINT_VIOLATION = 'P2002',
  UNPROCESSABLE_ENTITY = 'P2025',
}

export const ERROR_CODE_TO_HTTP_STATUS_MAP = {
  [PRISMA_CLIENT_ERROR_CODES.UNIQUE_CONSTRAINT_VIOLATION]: {
    statusCode: HttpStatus.CONFLICT,
    message: PRISMA_CLIENT_ERROR_MESSAGES.UNIQUE_CONSTRAINT_VIOLATION,
  },
  [PRISMA_CLIENT_ERROR_CODES.UNPROCESSABLE_ENTITY]: {
    statusCode: HttpStatus.UNPROCESSABLE_ENTITY,
    message: PRISMA_CLIENT_ERROR_MESSAGES.COULD_NOT_FIND_YOUR_ENTITY,
  },
};
